### ISSUE TITLE
iteminfo with korean characters and accesoryid & accname loading

### ISSUE THREAD

**Issue by sigtus** [Tokeiburu/RagnarokSDE#1]
This tool is simply awesome. The best one I witnessed regardint this edition field. I really thank you! However, I found two tiny bugs (or working as intended, I don't really know).
First, the item handlers throws exceptions if there're korean characters in item description or name. I use the iteminfo by zackdreaver's translation and had to delete a few lines the program informed me of throwing exceptions.
Second, it seems like the accname and accesoryid loadings are mixed. When I put up the values in the Lua settings folder, accesoryid.lua in the accesoryid field, and accname.lua in the accname field, it threw some errors regarding "no ACCESSORY_IDs" in accesoryid when trying to look up items like Angeling Hat. I tried a few times then changed the order, put accname in the accesoryid field and accesoryid field in accname, and the problem got solved instantly.
Gonna give a example of the first one with this file. I think I explained well the second one.
https://www.mediafire.com/?60hhwpa4ybl97w3
The version I use is 1.1.7.4.
And sorry for posting the issue here; I didn't know where I could post it (I couldn't find a way to reply on the rA forums...).

**Comment by Tokeiburu** [comment]
The ACCESSORY_IDs issue has been fixed (the labels were just misplaced), but the iteminfo issue is not something I can help with. The \ symbol is used for escaping characters. For example: \" means a quote, the client ignores those broken escape characters by removing the slash, but it'd be best to fix those instead.
