### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by Skormie** [Tokeiburu/RagnarokSDE#11]
Getting an unhandled exception when trying to load the item database of the most recent version of rAthena.

Sometimes this also shows as SDE.Core.FileParserException.

![image](https://user-images.githubusercontent.com/827520/148836194-8a94c4e8-331c-4be3-843b-316c33862534.png)

**Comment by Tokeiburu** [comment]
Sorry, I forgot to push the update for the new table format with card/enchant subtype. Updated in 1.2.1.8.
