### ISSUE TITLE
support new iteminfo v5 structure

### ISSUE THREAD

**Issue by ifahhad** [Tokeiburu/RagnarokSDE#4]
iteminfo has been updated by kRO , now they added a new row which is like this:

	[22978] = {
		unidentifiedDisplayName = "½¦µµ¿ì Å¥ºê(ÀÌ¾î¸µ)",
		unidentifiedResourceName = "È­·ÁÇÑ»óÀÚ",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "½¦µµ¿ì Å¥ºê(ÀÌ¾î¸µ)",
		identifiedResourceName = "È­·ÁÇÑ»óÀÚ",
		identifiedDescriptionName = {
			"´Ù¾çÇÑ Á¾·ùÀÇ Shadow Earring ¾ÆÀÌÅÛ Áß ÇÏ³ª¸¦ ¾òÀ» ¼ö ÀÖ´Â »óÀÚ.",
			"Weight:^009900 1^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},

i hope you can make SDE reads this new structure <3

**Comment by Tokeiburu** [comment]
Already fixed.
