### ISSUE TITLE
Weapon selection box won't show in skill_db

### ISSUE THREAD

**Issue by attackjom** [Tokeiburu/RagnarokSDE#9]
When edit skill_db  and try to change require-weapon, it won't show weapon selection box.

**Comment by Tokeiburu** [comment]
Updated version to 1.2.1.7. Though I barely use Github for those issues, so I'd recommend using rAthena's forums instead.

**Comment by attackjom** [comment]
sorry guys. In rathena, SDE editor download page don't have talk/support thread.
It would be good if you create a thread there.
